import Head from 'next/head';
import { FC, ReactNode } from 'react';
import {Navbar} from '../Navbar';
import styles from './MainLayout.module.css';
interface ChildrenProps {
  children?: ReactNode;
}

export const MainLayout:FC<ChildrenProps> = ({children}) => {
    return (
        <div className={styles.container}>

            <Head>
                <title>Home Percy</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <Navbar/>

            <main className={styles.main}>
                {children}

            </main>

        </div>
    )
}
